name: enviro_bank
description: Enviro Bank Limited loans app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  go_router: ^4.4.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  test:
  mockito:
  bloc_test: ^9.1.0
  build_runner:

flutter:
  generate: true
  uses-material-design: true


flutter_intl:
  enabled: true
